package org.example.Common.Enums;

public enum ProductType {
    AMARANTH_SEEDS("Amaranth seeds", 87, 5, "Plant these in the fall. Takes 7 days to grow. Harvest with the scythe."),
    ANCIENT_SEEDS("Ancient seeds", 500, 1, "Could these still grow?"),
    APPLE_SAPLING("Apple Sapling", 4000, -1, "Takes 28 days to produce a mature Apple tree. Bears fruit in the fall. Only grows if the 8 surrounding \"tiles\" are empty."),
    APRICOT_SAPLING("Apricot Sapling", 2000, -1, "Takes 28 days to produce a mature Apricot tree. Bears fruit in the spring. Only grows if the 8 surrounding \"tiles\" are empty."),
    ARTICHOKE_SEEDS("Artichoke seeds", 30, 5, "Plant these in the fall. Takes 8 days to mature."),
    BAMBOO_POLE("Bamboo Pole", 500, 1, "Use in the water to catch fish."),
    BANANA("Banana", 0, -1, ""),
    BAR("Bar", 0, -1, ""),
    BASIC_RETAINING_SOIL("Basic Retaining Soil", 100, -1, "This soil has a chance of staying watered overnight. Mix into tilled soil."),
    BEAN_STARTER("Bean Starter", 60, 5, "Plant these in the spring. Takes 10 days to mature, but keeps producing after that. Grows on a trellis."),
    BEER("Beer", 400, -1, "Drink in moderation."),
    BEET_SEEDS("Beet seeds", 20, 5, "Plant these in the fall. Takes 6 days to mature."),
    BIG_BARN("Big Barn", 12000, 1, "Houses 8 barn-dwelling animals. Allows animals to give birth. Unlocks goats."),
    BIG_COOP("Big Coop", 10000, 1, "Houses 8 coop-dwelling animals. Comes with an incubator. Unlocks ducks."),
    BLUEBERRY_SEEDS("Blueberry seeds", 80, 5, "Plant these in the summer. Takes 13 days to mature, and continues to produce after first harvest."),
    BOK_CHOY_SEEDS("Bok Choy seeds", 50, 5, "Plant these in the fall. Takes 4 days to mature."),
    BOUQUET("Bouquet", 1000, 2, "A gift that shows your romantic interest."),
    BREAD("Bread", 120, -1, "A crusty baguette."),
    BREAD_RECIPE("Bread Recipe", 100, 1, "A recipe to make Bread"),
    BROCCOLI_SEEDS("Broccoli seeds", 15, 5, "Plant in the fall. Takes 8 days to mature, and continues to produce after first harvest."),
    CABBAGE("Cabbage", 0, -1, ""),
    CAULIFLOWER_SEEDS("Cauliflower seeds", 80, 5, "Plant these in the spring. Takes 12 days to produce a large cauliflower."),
    CARROT_SEEDS("Carrot seeds", 5, 10, "Plant in the spring. Takes 3 days to grow."),
    CHERRY_SAPLING("Cherry Sapling", 3400, -1, "Takes 28 days to produce a mature Cherry tree. Bears fruit in the spring. Only grows if the 8 surrounding \"tiles\" are empty."),
    CHICKEN("Chicken", 800, 2, "Well cared-for adult chickens lay eggs every day. Lives in the coop."),
    COAL("Coal", 150, -1, "A combustible rock that is useful for crafting and smelting."),
    COFFEE("Coffee", 300, -1, "It smells delicious. This is sure to give you a boost."),
    COFFEE_BEAN("Coffee Bean", 200, 1, "Plant in spring or summer to grow a coffee plant. Place five beans in a keg to make coffee."),
    COPPER_ORE("Copper Ore", 75, -1, "A common ore that can be smelted into bars."),
    COPPER_TOOL("Copper Tool", 2000, 1, ""),
    COPPER_TRASH_CAN("Copper Trash Can", 1000, 1, ""),
    CORN_SEEDS("Corn seeds", 150, 5, "Plant these in the summer or fall. Takes 14 days to mature, and continues to produce after first harvest."),
    COW("Cow", 1500, 2, "Adults can be milked daily. Lives in the barn."),
    CRANBERRY_SEEDS("Cranberry seeds", 240, 5, "Plant these in the fall. Takes 7 days to mature, and continues to produce after first harvest."),
    CRANBERRY_SAUCE_RECIPE("Cranberry Sauce Recipe", 100, 1, "A recipe to make Cranberry Sauce"),
    CRANBERRY_SAUSE_RECIPE_2("Cranberry Sause Recipe", 100, 1, "A recipe to make Cranberry Sause"),
    DELUXE_BARN("Deluxe Barn", 25000, 1, "Houses 12 barn-dwelling animals. Comes with an auto-feed system. Unlocks sheep and pigs."),
    DELUXE_COOP("Deluxe Coop", 20000, 1, "Houses 12 coop-dwelling animals. Comes with an auto-feed system. Unlocks rabbits."),
    DELUXE_SPEED_GRO("Deluxe Speed-Gro", 150, -1, "Stimulates leaf production. Guaranteed to increase growth rate by at least 25%. Mix into tilled soil."),
    EGG("Egg", 0, -1, ""),
    EGGPLANT_SEEDS("Eggplant seeds", 20, 5, "Plant these in the fall. Takes 5 days to mature, and continues to produce after first harvest."),
    FAIRY_SEEDS("Fairy Seeds", 200, -1, "Plant in fall. Takes 12 days to grow. Produces a bright flower in a variety of colors."),
    FERTILIZER("Fertilizer", 100, -1, "Improves soil quality a little, increasing your chance to grow quality crops. Mix into tilled soil."),
    FISH_TACO_RECIPE("Fish Taco Recipe", 100, 1, "A recipe to make Fish Taco"),
    FISHING_ROD("Fishing Rod", 1800, 1, "Use in the water to catch fish."),
    FLOWER_SEEDS("Flower seeds", 40, 10, "Plant in the spring. Takes 6 days to bloom."),
    GARLIC_SEEDS("Garlic seeds", 40, 5, "Plant these in the spring. Takes 4 days to mature."),
    GOAT("Goat", 4000, 2, "Adults can be milked to produce goat milk. Lives in the barn."),
    GOAT_MILK("Goat Milk", 0, -1, ""),
    GOLD_ORE("Gold Ore", 450, -1, "A precious ore that can be smelted into bars."),
    GOLD_TOOL("Gold Tool", 10000, 1, ""),
    GOLD_TRASH_CAN("Gold Trash Can", 5000, 1, ""),
    GREEN_BEAN("Green Bean", 0, -1, ""),
    GREEN_BEAN_SEEDS("Green Bean seeds", 60, 5, "Plant these in the spring. Takes 10 days to mature, but keeps producing after that. Grows on a trellis."),
    HAY("Hay", 50, -1, "Animal food. Can be found in the wild or harvested from grass."),
    HOP_STARTER("Hop Starter", 60, 5, "Plant these in the summer. Takes 11 days to grow, but keeps producing after that. Grows on a trellis."),
    HOPS("Hops", 0, -1, ""),
    ICE_CREAM("Ice Cream", 250, -1, "It's hard to find someone who doesn't like this."),
    IRIDIUM_TOOL("Iridium Tool", 25000, 1, ""),
    IRIDIUM_TRASH_CAN("Iridium Trash Can", 12500, 1, ""),
    IRON_ORE("Iron Ore", 150, -1, "A fairly common ore that can be smelted into bars."),
    JAM("Jam", 0, -1, ""),
    JAZZ_SEEDS("Jazz seeds", 30, 5, "Plant in spring. Takes 7 days to produce a blue puffball flower."),
    KEG("Keg", 10000, 1, "Place a fruit or vegetable in here. Eventually it will turn into a beverage."),
    LARGE_EGG("Large Egg", 0, -1, ""),
    LETTUCE_SEEDS("Lettuce seeds", 25, 5, "Plant in summer. Takes 4 days to grow."),
    MAYONNAISE("Mayonnaise", 0, -1, ""),
    MAYONNAISE_MACHINE("Mayonnaise Machine", 2500, 1, "Turns eggs into mayonnaise."),
    MELON_SEEDS("Melon seeds", 80, 5, "Plant these in the summer. Takes 12 days to mature."),
    MILK("Milk", 0, -1, ""),
    MILK_PAIL("Milk Pail", 1000, 1, "Used to milk barn-dwelling animals."),
    OAK_RESIN("Oak Resin", 0, -1, ""),
    OIL("Oil", 0, -1, ""),
    OIL_MAKER("Oil Maker", 2500, 1, "Makes gourmet cooking oil from corn, sunflower seeds, or truffle."),
    ORANGE_SAPLING("Orange Sapling", 4000, -1, "Takes 28 days to produce a mature Orange tree. Bears fruit in the summer. Only grows if the 8 surrounding \"tiles\" are empty."),
    PIG("Pig", 16000, 2, "Searches for truffles underground. Lives in the barn."),
    PINE_TAR("Pine Tar", 0, -1, ""),
    POTATO_SEEDS("Potato seeds", 50, 5, "Plant these in the spring. Takes 6 days to mature, and has a chance of yielding multiple potatoes at harvest."),
    PRESERVES_JAR("Preserves Jar", 2000, 1, "Turns vegetables into pickles and fruit into jam."),
    PUMPKIN_SEEDS("Pumpkin seeds", 100, 5, "Plant these in the fall. Takes 13 days to mature."),
    RADISH_SEEDS("Radish seeds", 40, 5, "Plant these in the summer. Takes 6 days to mature."),
    RABBIT("Rabbit", 8000, 2, "Mature rabbits produce wool every few days. Lives in the coop."),
    RED_CABBAGE_SEEDS("Red Cabbage seeds", 100, 5, "Plant these in the summer. Takes 9 days to mature."),
    RHUBARB_SEEDS("Rhubarb seeds", 100, 5, "Plant these in the spring. Takes 13 days to mature."),
    SANDY_FLOWER("Sandy Flower", 0, -1, ""),
    SCARECROW("Scarecrow", 800, 1, "Protects your crops from crows."),
    SEED_MAKER("Seed Maker", 2500, 1, "Place a vegetable in here to grow seeds."),
    SHEEP("Sheep", 8000, 2, "Adults can be sheared for wool. Lives in the barn."),
    SLIME_EGG("Slime Egg", 0, -1, ""),
    SLIME_HUT("Slime Hut", 10000, 1, "Raises up to 20 slimes. Fills water trough and feeds automatically."),
    SPEED_GRO("Speed-Gro", 100, -1, "Stimulates leaf production. Increases growth rate by at least 10%. Mix into tilled soil."),
    SPRINKLER("Sprinkler", 2500, 1, "Waters 4 adjacent tiles every morning."),
    STARFRUIT_SEEDS("Starfruit seeds", 400, 5, "Plant these in the summer. Takes 13 days to mature."),
    STAR_SHARD("Star Shard", 0, -1, ""),
    STONE("Stone", 20, -1, ""),
    STRAWBERRY_SEEDS("Strawberry seeds", 100, 5, "Plant these in the spring. Takes 8 days to mature, and keeps producing strawberries after that."),
    STRAW_HAT("Straw Hat", 1000, 1, "A great hat for summer!"),
    SUGAR("Sugar", 100, -1, "Sweetens things up."),
    SUMMER_SEEDS("Summer seeds", 100, -1, "A variety of summer wild seeds."),
    SUNFLOWER_SEEDS("Sunflower seeds", 200, 5, "Plant these in summer or fall. Takes 8 days to grow. Yields more seeds at harvest."),
    SWEET_GEM_BERRY("Sweet Gem Berry", 0, -1, ""),
    TAPESTRY("Tapestry", 0, -1, ""),
    TOMATO_SEEDS("Tomato seeds", 50, 5, "Plant these in the summer. Takes 11 days to mature, and continues to produce after first harvest."),
    TORCH("Torch", 30, -1, "Provides light. Useful for exploring caves."),
    TRUFFLE("Truffle", 0, -1, ""),
    TURNIP_SEEDS("Turnip seeds", 25, 5, "Plant in spring. Takes 5 days to grow."),
    WHEAT("Wheat", 0, -1, ""),
    WHEAT_FLOUR("Wheat Flour", 100, -1, "Used for baking. Can be milled from wheat."),
    WHEAT_SEEDS("Wheat seeds", 10, 5, "Plant these in the summer or fall. Takes 4 days to mature."),
    WHITE_ALGAE("White Algae", 0, -1, ""),
    WOOD("Wood", 10, -1, ""),
    WOOL("Wool", 0, -1, ""),
    YAM_SEEDS("Yam seeds", 60, 5, "Plant these in the fall. Takes 10 days to mature.");



public final String displayName;
    public final int price;
    public final int limit;
    public final String description;

    ProductType(String displayName, int price, int limit, String description) {
        this.displayName = displayName;
        this.price = price;
        this.limit = limit;
        this.description = description;
    }
}
